const ENV = {
  BASE: 'https://alpha.consensysidentity.com',
  VERSION: '/v1',
  TENANT: '/tenant',
  FEEDS: '/feeds',
  SCHEMAS: '/schemas',
  AGENT: '/agent',
}

// const ENDPOINTS = {
//   BASE: ENV.BASE,
//   VERSION: ENV.BASE + ENV.VERSION,
//   TENANT: ENV.BASE + ENV.VERSION + ENV.TENANT,
//   AGENT: ENV.BASE + ENV.VERSION + ENV.TENANT + ENV.AGENT,
//   FEEDS: ENV.BASE + ENV.VERSION + ENV.FEEDS,
//   SCHEMAS: ENV.BASE + ENV.VERSION + ENV.FEEDS + ENV.SCHEMAS,
// }

// const MESSAGE_TYPES = {
//   AUTH_REQUEST: 'AUTH_REQUEST',
//   CONNECT_REQUEST: 'CONNECT_REQUEST',
//   CONNECT_RESPONSE: 'CONNECT_RESPONSE',
//   DISCLOSURE_REQUEST: 'DISCLOSURE_REQUEST',
//   DISCLOSURE_RESPONSE: 'DISCLOSURE_RESPONSE',
// }

const SOURCE_TYPE = 'TRUST_AGENT_ID_WALLET'

const ENDPOINTS = (config: { root: string }) => {
  const ENV = {
    BASE: `https://${config.root}`,
    VERSION: '/v1',
    TENANT: '/tenant',
    FEEDS: '/feeds',
    SCHEMAS: '/schemas',
    AGENT: '/agent',
  }
  return {
    BASE: ENV.BASE,
    VERSION: ENV.BASE + ENV.VERSION,
    TENANT: ENV.BASE + ENV.VERSION + ENV.TENANT,
    AGENT: ENV.BASE + ENV.VERSION + ENV.TENANT + ENV.AGENT,
    FEEDS: ENV.BASE + ENV.VERSION + ENV.FEEDS,
    SCHEMAS: ENV.BASE + ENV.VERSION + ENV.FEEDS + ENV.SCHEMAS,
  }
}

export { ENDPOINTS, SOURCE_TYPE }
